# 第2回演習「NumPyによる行列の記述」

この演習では数値計算ライブラリを用いた行列の記述方法を習得します。<hr />


## 【2-1】はじめてのNumPy
<img src="https://pfe.p.cyber-u.ac.jp/img/Python/Week2/2-1.png" style="margin:30px;float: left;width:400px;">
<div style="clear: both;"></div>
上の画像を見ながら、配列の中身を出力させるプログラムを作成しましょう。

In [1]:
# ↓ここにプログラムを書き、Shift + Enter で実行します。
import numpy as np
x=np.array([1,2,3])
print(x)
print(x[0])

[1 2 3]
1


## 【2-2】行ベクトルの加算
<img src="https://pfe.p.cyber-u.ac.jp/img/Python/Week2/2-2.png" style="margin:30px;float: left;width:500px;">
<div style="clear: both;"></div>
上の画像を見ながら x と y の和を出力するプログラムを作成しましょう。<br />
x には、上の2-1で既に[1,2,3]が代入されています。

In [2]:
# ↓ここにプログラムを書き、Shift + Enter で実行します。
# xにはすでに[1,2,3]が代入されています。
y=np.array([1,2,3])
print(x+y)

[2 4 6]


## 【2-3】成分の書き換え
<img src="https://pfe.p.cyber-u.ac.jp/img/Python/Week2/2-3.png" style="margin:30px;float: left;width:500px;">
<div style="clear: both;"></div>
上の画像を見ながら、配列の0番目の値を書き換えるプログラムを作成しましょう。<br />
xにはすでに[1,2,3]が代入されています。

In [3]:
# ↓ここにプログラムを書き… は以後、割愛します。
x[0]=100
print(x)

[100   2   3]


## 【2-4】2次元にすると行列らしくなる
<img src="https://pfe.p.cyber-u.ac.jp/img/Python/Week2/2-4.png" style="margin:30px;float: left;width:500px;">
<div style="clear: both;"></div>
上の画像を見ながら、行列(このプログラム中では2次元の配列)の中身を出力する<br />
プログラムを作成しましょう。<br />
x[0][1] や x[1][2] とはそれぞれどこなのか? と意識しながら書きましょう。<br />
最後に2次元配列のサイズ(行数と列数)も出力させましょう。

In [4]:
# ↓ここにプログラム…
x=np.array([[1,2,3],[4,5,6]])
print(x)
print(x[0][1])
print(x[1][2])
print(x.shape)
m,n=x.shape
print(m)
print(n)

[[1 2 3]
 [4 5 6]]
2
6
(2, 3)
2
3


## 【2-5】ゼロで埋める
<img src="https://pfe.p.cyber-u.ac.jp/img/Python/Week2/2-5.png" style="margin:30px;float: left;width:600px;">
<div style="clear: both;"></div>
上の画像を見ながら、全ての成分が0の配列を作って出力させましょう。<br />
2次元の配列も作って出力させましょう。型(dtype)を指定する時としない時で、<br />
何が変わるでしょうか?

In [5]:
# ↓ここにプ…
x=np.zeros(10)
print(x)
x=np.zeros((2,3))
print(x)
x=np.zeros((2,3),dtype='int')
print(x)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[[0 0 0]
 [0 0 0]]


## 【2-6】1で埋める
<img src="https://pfe.p.cyber-u.ac.jp/img/Python/Week2/2-6.png" style="margin:30px;float: left;width:760px;">
<div style="clear: both;"></div>
上の画像を見ながら、全ての成分が1の配列を作って出力させましょう。<br />
2-5 の手順とよく似ています。<br />
型(dtype)も指定しましょう。

In [6]:
# ↓ここ…
x=np.ones((3,4),dtype='int')
print(x)


[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


## 【2-7】ランダムな行列を作る
<img src="https://pfe.p.cyber-u.ac.jp/img/Python/Week2/2-7.png" style="margin:30px;float: left;width:720px;">
<div style="clear: both;"></div>
上の画像を見ながら、ランダムな成分の行列(2次元の配列)を作って出力させましょう。<br />
ランダムな成分の値は「0以上1未満」です。<br />
ランダムな整数を得る方法も使いましょう。

In [7]:
# 2-7 ランダムな行列を作る
x=np.random.rand(4,5)
print(x)
x=np.random.randint(5,10,(4,5))
print(x)


[[0.14362139 0.77071633 0.315465   0.85434878 0.59720728]
 [0.17138198 0.63062416 0.27563269 0.8545931  0.57807085]
 [0.25061213 0.63731848 0.56299076 0.12360976 0.10825951]
 [0.06717173 0.46523984 0.77887411 0.50025139 0.04274601]]
[[6 7 7 9 6]
 [8 5 6 6 5]
 [8 5 9 8 6]
 [5 8 7 5 6]]


## 【2-8】行列の加算と減算
<img src="https://pfe.p.cyber-u.ac.jp/img/Python/Week2/2-8.png" style="margin:30px;float: left;width:400px;">
<div style="clear: both;"></div>
上の画像を見ながら行列の加算、減算のプログラムを作成しましょう。<br />
それぞれ、どの成分が足されたり、引かれたりするかを見ましょう。

In [8]:
x=np.array([[1,2,3],[4,5,6]])
y=np.array([[1,1,1],[1,1,1]])
print(x+y)
print(x-y)

[[2 3 4]
 [5 6 7]]
[[0 1 2]
 [3 4 5]]


## 【2-9】スカラー倍
<img src="https://pfe.p.cyber-u.ac.jp/img/Python/Week2/2-9.png" style="margin:30px;float: left;width:400px;">
<div style="clear: both;"></div>
上の画像を見ながら、行列のスカラー倍を出力させるプログラムを作成しましょう。<br />
次の 2-10 にある行列の積とは、何が違うでしょうか?

In [9]:
print(x*10)

[[10 20 30]
 [40 50 60]]


## 【2-10】行列の積
<img src="https://pfe.p.cyber-u.ac.jp/img/Python/Week2/2-10.png" style="margin:30px;float: left;width:500px;">
<div style="clear: both;"></div>
上の画像を見ながら、行列の積を求めるプログラムを作成しましょう。<br />
積は順番に注意が必要です。一般に行列の AB=BA は成り立ちません。

In [10]:
v=np.array([[1,2],[3,4]])
w=np.array([[5,6],[7,8]])
print(v)
print(w)
print(v.dot(w)) # 積を出力

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[19 22]
 [43 50]]


## 【2-11】便利なスライシング
<img src="https://pfe.p.cyber-u.ac.jp/img/Python/Week2/2-11.png" style="margin:30px;float: left;width:760px;">
<div style="clear: both;"></div>
上の画像を見ながら、行列に対するスライシングの機能を試しましょう。<br />
好きな箇所を切り出したり、逆順に並べることもできます。

In [11]:
x=np.array([0,1,2,3,4,5,6,7,8,9])
print(x[:3])
print(x[3:])
print(x[3:8])
print(x[3:8:2])
print(x[::-1])
x=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(x)
print(x[:2,:3])

[0 1 2]
[3 4 5 6 7 8 9]
[3 4 5 6 7]
[3 5 7]
[9 8 7 6 5 4 3 2 1 0]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[1 2 3]
 [5 6 7]]


## 【2-12】転置行列
<img src="https://pfe.p.cyber-u.ac.jp/img/Python/Week2/2-12.png" style="margin:30px;float: left;width:640px;">
<div style="clear: both;"></div>
上の画像を見ながら、転置行列のプログラムを作成しましょう。<br />
行と列が入れ替わります。<br />
入れ替えたものを再度入れ替えたら、元に戻りますか?

In [13]:
x=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(x.T)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


## 【2-13】転置行列の続き
<img src="https://pfe.p.cyber-u.ac.jp/img/Python/Week2/2-13.png" style="margin:30px;float: left;width:550px;">
<div style="clear: both;"></div>
上の画像を見ながら、行ベクトルの転置や列ベクトルの転置を行いましょう。<br />
列ベクトルの書き方に注意しましょう。

In [14]:
x=np.array([[1,2,3]])
print(x.T)
x=np.array([[1],[2],[3]])
print(x.T)

[[1]
 [2]
 [3]]
[[1 2 3]]


## 【2-14】アダマール積
<img src="https://pfe.p.cyber-u.ac.jp/img/Python/Week2/2-14.png" style="margin:30px;float: left;width:500px;">
<div style="clear: both;"></div>
上の画像を見ながら、行列のアダマール積を求めるプログラムを<br />
作成しましょう。大仰な名前がついていますが、やっていることは各成分の掛け算です。

In [15]:
x=np.array([1,2,3])
y=np.array([4,5,6])
print(x*y)

[ 4 10 18]


## 【2-15】単位行列
<img src="https://pfe.p.cyber-u.ac.jp/img/Python/Week2/2-15.png" style="margin:30px;float: left;width:720px;">
<div style="clear: both;"></div>
上の画像を見ながら、3行3列の単位行列を出力するプログラムを<br />
作成しましょう。対角成分が1で、それ以外の成分が0になります。<br />
余力があったら3*3以外も試しましょう。

In [19]:
print(np.identity(3))
print(np.identity(3,dtype='int'))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]


## 【2-16】逆行列
<img src="https://pfe.p.cyber-u.ac.jp/img/Python/Week2/2-16.png" style="margin:30px;float: left;width:500px;">
<div style="clear: both;"></div>
上の画像を見ながら、逆行列を求めるプログラムを<br />
作成しましょう。余力があったら、逆行列と元の行列の積を求めましょう。
<hr />

In [23]:
p=np.array([[3,1,1],[4,3,-1],[8,4,1]])
q=np.linalg.inv(p) # 逆行列
print(q)
print(p.dot(q))
print(q.dot(p))

[[  7.   3.  -4.]
 [-12.  -5.   7.]
 [ -8.  -4.   5.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


ここまでで、第2回第2章は終了です。お疲れさまでした。
一息入れて、第3章の講義に進んでください。